routes:
  # Dashboard
  /phpinfo:
    uses: phpinfo
    as: phpinfo

  /logs:
    uses: logs
    as: logs

  /rebuild-search:
    uses: rebuildSearchIndex
    as: powertools.rebuild-search

  /clear-cache:
    uses: clearCache
    as: powertools.clear-cache
  /clear-static:
    uses: clearStaticCache
    as: powertools.clear-static
  /update-stache:
    uses: updateStache
    as: powertools.update-stache

  /assets-generate-presets:
    uses: generatePresets
    as: powertools.assets-generate-presets
  /assets-regenerate-presets:
    uses: regeneratePresets
    as: powertools.assets-regenerate-presets