routes:
  # Dashboard
  /:
    uses: phpinfo
    as: phpinfo

  /rebuild-search: rebuildSearchIndex

  /clear-cache: clearCache
  /clear-static: clearStaticCache
  /update-stache: updateStache

  /assets-generate-presets: generatePresets
  /assets-regenerate-presets: regeneratePresets